version: 2
build:
   os: ubuntu-22.04
   tools:
      python: "3.11"

# Build documentation with sphinx
sphinx:
   configuration: docs/conf.py

# Dependencies required to build your docs
python:
   install:
   - requirements: requirements_doc.txt

