% Test Matlabbatch
- decide whether output files are written in same directory or different one
=> maybe output-dir as physio-parameter? (model? log_files? verbose?)
- try out auto-peak detection; manual; post-hoc
- write matlabbatch job-file for every of the 4 examples

% Extension Matlabbatch
- plotting via spm_uitab
- write toolbox menu => check in SnPM.m:

spm.tools.physio should be known, if in toolbox-directory!

[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Statistical non-Parametric Mapping (SnPM)');
snpm_init; % Initialize Matlab Batch system
snpm('AsciiWelcome')
spm_help('!Disp','snpm.m','','Graphics',snpm('Ver'))
snpm('CreateMenuWin')

elseif strcmp(lower(Action),lower('CreateMenuWin'))
    fig = spm_figure('GetWin','Interactive');
    h0  = uimenu(fig,...
        'Label',	'SnPM13',...
        'Separator',	'on',...
        'Tag',		'SnPM13',...
        'HandleVisibility','on');
    h1  = uimenu(h0,...
        'Label',	'Specify',...
        'Separator',	'off',...
        'Tag',		'Specify',...
        'HandleVisibility','on');
    h1_1  = uimenu(h1,...
        'Label',	'SingleSub: Two Sample T test; 2 conditions, replications',...
        'Separator',	'off',...
        'Tag',		'TwoSampTss',...
        'CallBack','spm_jobman(''interactive'','''',''spm.tools.snpm.des.TwoSampTss'');',...
        'HandleVisibility','on');

